server:
  port: 8081

spring:
  application:
    name: authentication-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/apiflow_auth}
    username: ${DB_USERNAME:apiflow}
    password: ${DB_PASSWORD:apiflow}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

apiflow:
  security:
    jwt:
      secret: ${JWT_SECRET:change-this-to-a-long-random-secret-value-in-prod-please}
      access-token-expiration-ms: ${JWT_ACCESS_EXP_MS:900000}
      refresh-token-expiration-ms: ${JWT_REFRESH_EXP_MS:604800000}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
